### ISSUE TITLE
Refactor threading framework

### ISSUE THREAD

**Issue by ktkrg** [opendistro-for-elasticsearch/performance-analyzer-rca#105]
### Overview
Currently the PA engine process spins up multiple threads in different places in order to run the reader, and the RCA. We need to consolidate the these executor/thread creation, rethink the execution hierarchy, and handle missed cases of error handling.

When Performance Analyzer engine is started, it should spawn a top level thread(or reuse the main thread as the top level thread) to then spin up a new thread for the following concurrent activities:

1. PA Reader
1. gRPC server
1. HTTP/1.x server for cURL and perf-top usecases
1. RCA controller

### Top level thread functionality
The top level thread spawns the necessary high level secondary threads. Once that is done, it just blocks on the error queue and waits for an exception to be put in the queue. If it sees an error in the queue, it dequeues the error, handles the error appropriately and continues to block on the queue for the lifetime of the agent.

### Thread provisioning
Whenever a new second-level thread is needed, the top level thread also passes in an callback to the second level runnable, so that the child thread can signal the top level thread if it runs into any error that it wishes to notify the parent.

The top level thread also uses the information from provisioning for accounting purposes.

### Consolidation of RCA executors
This only captures the high level idea and not the specifics.

We need to move the scheduler off of the ScheduledExecutorService into its own thread which again, runs in a loop, evaluates the graph and sleeps for the remainder of the second if it finishes early.

The multi-nanny executor can be run as part of the second-level RCA controller itself instead of it having its own executor and separate error handling threads.

**_PHASE 1_**
* Create top level controller
* Provision the above threads from the top level controller

**Testing**
Broadly speaking all of the following components need to be tested
* Reader tests
  * Ensure reader is working as expected, creating db files, emitting stats(metrics) in all configurations
  * [Placeholder: Tests for error conditions the previous implementation would've missed]
* RCA tests
  * Ensure RCA is working as expected, enable/disable, setting up and tearing down of executors, and error handling threads.
  * [Placeholder: Tests for error conditions the previous implementation would've missed]
* perftop and curl tests
  * Ensure curl'd requests return valid responses, perf-top dashboards are showing all metrics.
  * [Placeholder: Tests for error conditions the previous implementation would've missed]

**Comment by yojs** [comment]
`the top level thread also passes in an listener to ..` should this be callback ?

In the  "Consolidation of RCA executors", we should probably mention the rationale so that people understand why ?

The phase 1 testing should include the cases that exercise the error paths and see how the new one handles them. Of course the happy case should continue to work as they should

**Comment by ktkrg** [comment]
> the top level thread also passes in an listener to .. should this be callback ?

I meant callback. Updated.

> The phase 1 testing should include the cases that exercise the error paths and see how the new one handles them.

Added a placeholder in the issue. Will update the issue when I have a list.
