### ISSUE TITLE
FileGCTest fails intermittently during CI workflow

### ISSUE THREAD

**Issue by ktkrg** [opendistro-for-elasticsearch/performance-analyzer-rca#123]
One of the unit tests in the FileGCTest - testTimeBasedFileCleanUp() fails intermittently when it is being run as part of the CI workflow.

The test passes consistently on a mac and on Amazon Linux 2012.

**Comment by sidheart** [comment]
My commit [here](https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/commit/3267f003f4b5acc70f8c603472cc1ed44859a310) seems to have fixed this issue. It was related to having too strict testing bounds (e.g. order 10s of milliseconds instead of 100s).
