### ISSUE TITLE
Release Performance Analyser Root Cause Analysis Framework

### ISSUE THREAD

**Issue by weicongs-amazon** [opendistro-for-elasticsearch/performance-analyzer-rca#232]
Security Review on-going

**Comment by peterzhuamazon** [comment]
RCA is now part of the PA in ODFE 1.9.0 Release.
https://opendistro.github.io/for-elasticsearch/blog/odfe-updates/2020/07/Open-Distro-for-Elasticsearch-1.9.0-is-released/
