### ISSUE TITLE
Investigate error messages from sqlite batch upload

### ISSUE THREAD

**Issue by ditac** [opendistro-for-elasticsearch/performance-analyzer-rca#39]
We see the following error messages when batch inserting data into sqlite - 

"Single batch : No bind variables have been provided with a single statement batch execution." We have checks in the code to not insert to sqlite if batch size is zero. We need to check if there are edge cases where the size check is not working.

**Comment by ktkrg** [comment]
This is not related to #435, closing this issue as we recently upgraded sqlite. Will create a new issue if this persists.
